/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * EntityEditor.java
 *
 * Created on Jan 23, 2011, 4:04:05 PM
 */

package edu.vt.workspace.components;

import edu.vt.workspace.components.utilities.EntityTypeRenderer;
import edu.vt.workspace.data.AWEntity;
import edu.vt.workspace.data.EntityManager;
import java.util.Set;

/**
 *
 * @author cpa
 */
public class EntityEditor extends javax.swing.JDialog {
private AWEntity _entity;
    /** Creates new form EntityEditor */
    public EntityEditor(java.awt.Frame parent, AWEntity entity, boolean modal) {
        super(parent, modal);
        _entity = entity;     
        initComponents();
        loadTypes();
        entityValueField.setText(_entity.getValue());
    }



      /**
     * This method is called after the type menu to populate it
     */
    private void loadTypes() {
        Set<String> types = EntityManager.getInstance().getEntityTypes();
        typeList.addItem("Please chose a type for this entity");
        for (String type : types) {
            typeList.addItem(type);
        }

        typeList.addItem("Define new type");
        typeList.setRenderer(new EntityTypeRenderer());

        if (types.size() > 0)
            typeList.setSelectedIndex(0);

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        entityValueField = new javax.swing.JTextField();
        typeList = new javax.swing.JComboBox();
        saveButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        entityTypeText = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Entity Editor");
        setResizable(false);

        jLabel1.setText("Name:");

        jLabel2.setText("Type:");

        entityValueField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entityValueFieldActionPerformed(evt);
            }
        });
        entityValueField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                entityValueFieldKeyTyped(evt);
            }
        });

        typeList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeListActionPerformed(evt);
            }
        });

        saveButton.setText("Save Entity");
        saveButton.setEnabled(false);
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        jLabel3.setText("New Type:");

        entityTypeText.setText("<new type>");
        entityTypeText.setEnabled(false);
        entityTypeText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entityTypeTextActionPerformed(evt);
            }
        });
        entityTypeText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                entityTypeTextFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                entityTypeTextFocusLost(evt);
            }
        });
        entityTypeText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                entityTypeTextKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(typeList, 0, 297, Short.MAX_VALUE)
                            .addComponent(entityTypeText, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 297, Short.MAX_VALUE)
                            .addComponent(entityValueField, javax.swing.GroupLayout.DEFAULT_SIZE, 297, Short.MAX_VALUE))
                        .addGap(31, 31, 31))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(cancelButton)
                        .addGap(18, 18, 18)
                        .addComponent(saveButton)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(entityValueField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(typeList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(entityTypeText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveButton)
                    .addComponent(cancelButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        _entity.setValue(entityValueField.getText());
        if (typeList.getSelectedIndex() < typeList.getItemCount() - 1) {
            _entity.setType((String) typeList.getSelectedItem());
        } else if (typeList.getSelectedIndex() == typeList.getItemCount() - 1 && !entityTypeText.getText().equals("<new type>")) {
            _entity.setType(entityTypeText.getText());
        }
        setVisible(false);
    }//GEN-LAST:event_saveButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed

        setVisible(false);
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void entityTypeTextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_entityTypeTextFocusGained
        if (entityTypeText.getText().equals("<new type>")) {
           entityTypeText.setText("");
       }
    }//GEN-LAST:event_entityTypeTextFocusGained

    private void entityTypeTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_entityTypeTextFocusLost
        if (entityTypeText.getText().length() == 0){
            entityTypeText.setText("<new type>");
        }
    }//GEN-LAST:event_entityTypeTextFocusLost

    private void entityValueFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entityValueFieldActionPerformed
        saveButton.setEnabled(isValidEntity());

    }//GEN-LAST:event_entityValueFieldActionPerformed

    private void typeListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeListActionPerformed
        saveButton.setEnabled(isValidEntity());
        entityTypeText.setEnabled(typeList.getSelectedIndex() == typeList.getItemCount() - 1);
        
    }//GEN-LAST:event_typeListActionPerformed

    private void entityTypeTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entityTypeTextActionPerformed
        saveButton.setEnabled(isValidEntity());
        
    }//GEN-LAST:event_entityTypeTextActionPerformed

    private void entityValueFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_entityValueFieldKeyTyped
         saveButton.setEnabled(isValidEntity());
    }//GEN-LAST:event_entityValueFieldKeyTyped

    private void entityTypeTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_entityTypeTextKeyTyped
        saveButton.setEnabled(isValidEntity());      
    }//GEN-LAST:event_entityTypeTextKeyTyped

public boolean isValidEntity(){
    return entityValueField.getText().length() > 0 && typeList.getSelectedIndex() > 0
            && (typeList.getSelectedIndex() < typeList.getItemCount() - 1 || (entityTypeText.getText().length() > 0 &&! entityTypeText.getText().equals("<new type>"))) ;
    //return _entity.getValue().length() > 0 && _entity.getType().length() > 0;
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JTextField entityTypeText;
    private javax.swing.JTextField entityValueField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton saveButton;
    private javax.swing.JComboBox typeList;
    // End of variables declaration//GEN-END:variables

}
